name: Publish
on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.1.0

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version number
        id: vars
        run: echo ::set-output name=version::$(jq -r .version package.json)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy NPM packages (FIXME)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec npm publish
          